# Generated by Django 4.2.6 on 2023-10-23 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='donations',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprojectrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
