# Generated by Django 4.2.6 on 2023-10-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectsmodel_donations_donationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
