# Generated by Django 4.2.6 on 2023-10-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_donationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreportmodel',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commentsmodel'),
        ),
    ]
