# Generated by Django 4.2.6 on 2023-10-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_commentreportmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreportmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel'),
        ),
    ]
