# Generated by Django 4.2.6 on 2023-10-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_commentreportmodel_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreportmodel',
            name='project',
        ),
    ]
