# Generated by Django 4.2.7 on 2023-12-16 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_userprojectrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='details',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='userprojectrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
