# Generated by Django 4.2.7 on 2024-01-15 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectsmodel_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
