# Generated by Django 4.2.7 on 2024-01-16 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_donationmodel_is_deleted_projectsmodel_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='details',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
