# Generated by Django 4.2.7 on 2024-01-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projectsmodel_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='start_time',
            field=models.DateField(),
        ),
    ]
