# Generated by Django 4.2.7 on 2024-01-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectsmodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='details',
            field=models.TextField(max_length=3000),
        ),
    ]
